"""macOS `.app` bundle builder.

Produces a real double-clickable bundle. Two modes, and the difference is
stated in the output rather than hidden:

* **launcher bundle** (default) -- `Contents/MacOS/UnifiedAgent` is a small
  script that runs the installed package with the interpreter it was built
  with. Fast, zero extra dependencies, and it keeps working as long as the
  environment it points at exists. Moving or deleting that virtualenv breaks
  it, which is why the path is written into the bundle explicitly.
* **frozen bundle** (`--frozen`) -- PyInstaller collects the interpreter and
  dependencies into the bundle, so it is self-contained and relocatable.
  Needs PyInstaller installed; the command says so instead of failing late.

The icon is generated procedurally with nothing but the standard library:
a tiny PNG encoder plus `iconutil` (present on every macOS) to assemble the
`.icns`. Adding a drawing dependency to ship one icon would be silly.
"""

from __future__ import annotations

import functools
import os
import shutil
import struct
import subprocess
import sys
import tempfile
import time
import zlib
from dataclasses import dataclass
from pathlib import Path

BUNDLE_ID = "dev.unifiedai.agent"
APP_NAME = "UnifiedAgent"

# Palette, matching the console so the icon and the app agree.
BG = (14, 17, 22, 255)  # #0e1116
ACCENT = (76, 141, 255, 255)  # #4c8dff
INK = (230, 237, 243, 255)  # #e6edf3

ICONSET_SIZES = [16, 32, 64, 128, 256, 512, 1024]

# `iconutil` rejects any staging directory not named `*.iconset`, with the
# unhelpful message "Invalid Iconset". Named here so the rule is a constant
# that can be asserted without needing iconutil installed.
ICONSET_NAME = "uaa.iconset"

INFO_PLIST = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>{name}</string>
  <key>CFBundleDisplayName</key><string>{display}</string>
  <key>CFBundleIdentifier</key><string>{bundle_id}</string>
  <key>CFBundleExecutable</key><string>{executable}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>{version}</string>
  <key>CFBundleVersion</key><string>{version}</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSUIElement</key><false/>
  <key>NSSupportsAutomaticGraphicsSwitching</key><true/>
  <key>NSHumanReadableCopyright</key><string>{copyright}</string>
</dict>
</plist>
"""

LAUNCHER_SCRIPT = """#!/bin/sh
# Generated by `uaa desktop --bundle`.
#
# This bundle launches the unified-ai-agent package with the interpreter it
# was built against. If that interpreter is gone, the script falls back to
# whatever `python3` is on PATH and says what happened rather than exiting
# silently -- a double-clicked app that does nothing is the worst outcome.
set -eu

PYTHON="{python}"
LOG="$HOME/Library/Logs/unified-ai-agent.log"
mkdir -p "$(dirname "$LOG")"

if [ ! -x "$PYTHON" ]; then
  echo "uaa: the interpreter this app was built against is missing:" >&2
  echo "     $PYTHON" >&2
  if command -v python3 >/dev/null 2>&1; then
    echo "uaa: falling back to $(command -v python3)" >&2
    PYTHON="$(command -v python3)"
  else
    echo "uaa: no python3 on PATH either. Reinstall with:" >&2
    echo "     pip install -e '.[desktop]' && uaa desktop --bundle" >&2
    exit 1
  fi
fi

exec "$PYTHON" -m unified_agent.desktop "$@" >>"$LOG" 2>&1
"""


class BundleError(RuntimeError):
    pass


# ---------------------------------------------------------------------------
# minimal PNG writer
# ---------------------------------------------------------------------------


def write_png(path: Path, width: int, height: int, rgba: bytes) -> None:
    """Write an 8-bit RGBA PNG. No filter, one IDAT chunk."""
    if len(rgba) != width * height * 4:
        raise ValueError(f"expected {width * height * 4} bytes, got {len(rgba)}")

    raw = bytearray()
    stride = width * 4
    for y in range(height):
        raw.append(0)  # filter type 0 (None)
        raw += rgba[y * stride : (y + 1) * stride]

    def chunk(tag: bytes, payload: bytes) -> bytes:
        return (
            struct.pack(">I", len(payload))
            + tag
            + payload
            + struct.pack(">I", zlib.crc32(tag + payload) & 0xFFFFFFFF)
        )

    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    png = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )
    path.write_bytes(png)


# ---------------------------------------------------------------------------
# procedural icon
# ---------------------------------------------------------------------------
#
# Nothing here imports a drawing library. One icon is not worth adding a
# dependency to a project whose selling point is that it has none, and the
# standard library already has what is needed: a hand-rolled PNG encoder plus
# `iconutil`, which ships with macOS.


def _rounded_rect_coverage(x: float, y: float, size: float, radius: float) -> bool:
    """Is (x, y) inside a rounded square of `size` with corner `radius`?"""
    if x < 0 or y < 0 or x > size or y > size:
        return False
    cx = min(max(x, radius), size - radius)
    cy = min(max(y, radius), size - radius)
    dx, dy = x - cx, y - cy
    return dx * dx + dy * dy <= radius * radius


def _stroke_coverage(
    x: float, y: float, ax: float, ay: float, bx: float, by: float, width: float
) -> bool:
    """Distance from (x, y) to segment a-b, compared against half `width`."""
    vx, vy = bx - ax, by - ay
    wx, wy = x - ax, y - ay
    length_sq = vx * vx + vy * vy
    t = 0.0 if length_sq == 0 else max(0.0, min(1.0, (wx * vx + wy * vy) / length_sq))
    px, py = ax + t * vx, ay + t * vy
    dx, dy = x - px, y - py
    return dx * dx + dy * dy <= (width / 2) ** 2


def _supersample_for(size: int) -> int:
    """How many samples per output pixel this size needs.

    A flat 4x costs ~17 million Python iterations at 1024 px, which turns
    `uaa desktop --bundle` into a multi-minute command. Above ~256 px the
    output is already larger than any display, so the extra samples buy
    nothing visible and cost seconds.
    """
    if size <= 64:
        return 4
    if size <= 256:
        return 2
    return 1


@functools.lru_cache(maxsize=32)
def render_icon(size: int, supersample: int | None = None) -> bytes:
    """Draw the app mark: a terminal prompt chevron on a rounded dark tile.

    Supersampled and averaged, because a 16 px icon with hard edges looks
    broken and `iconutil` will accept it anyway. Cached, because the bundle
    asks for the same pixel sizes twice -- once as `icon_NxN.png`, once as the
    `@2x` variant of a smaller size.
    """
    samples = supersample or _supersample_for(size)
    n = size * samples
    scale = n / 1024.0

    radius = 224 * scale
    stroke = 108 * scale
    # Chevron vertices in 1024-space, then scaled.
    ax, ay = 300 * scale, 330 * scale
    bx, by = 470 * scale, 512 * scale
    cx, cy = 300 * scale, 694 * scale
    # The trailing rule of a shell prompt: a caret followed by a bar.
    bar_x0, bar_x1 = 560 * scale, 730 * scale
    bar_y = 694 * scale

    accum = [[0, 0, 0, 0] for _ in range(size * size)]
    for sy in range(n):
        fy = sy + 0.5
        row = (sy // samples) * size
        for sx in range(n):
            fx = sx + 0.5
            if not _rounded_rect_coverage(fx, fy, n, radius):
                continue
            colour = BG
            if _stroke_coverage(fx, fy, ax, ay, bx, by, stroke) or _stroke_coverage(
                fx, fy, bx, by, cx, cy, stroke
            ):
                colour = ACCENT
            elif _stroke_coverage(fx, fy, bar_x0, bar_y, bar_x1, bar_y, stroke * 0.78):
                colour = INK
            slot = accum[row + sx // samples]
            slot[0] += colour[0]
            slot[1] += colour[1]
            slot[2] += colour[2]
            slot[3] += colour[3]

    total = samples * samples
    out = bytearray(size * size * 4)
    for i, (r, g, b, a) in enumerate(accum):
        if a == 0:
            # Entirely outside the tile: stay transparent rather than black,
            # or the rounded corners render as dark squares.
            continue
        out[i * 4 + 0] = r // total
        out[i * 4 + 1] = g // total
        out[i * 4 + 2] = b // total
        out[i * 4 + 3] = min(255, a // total)
    return bytes(out)


@dataclass
class IconResult:
    path: Path | None
    reason: str = ""

    def __bool__(self) -> bool:
        return self.path is not None


def iconutil_path() -> str | None:
    """Locate `iconutil`, or None. Split out so callers (and tests) can ask
    the question without attempting a build."""
    found = shutil.which("iconutil")
    if found:
        return found
    return "/usr/bin/iconutil" if Path("/usr/bin/iconutil").exists() else None


def build_icns(target_dir: Path) -> IconResult:
    """Assemble AppIcon.icns.

    Returns a reason on failure rather than a bare None: "no icon" and
    "iconutil refused the iconset" are different problems, and collapsing
    them sends the user looking for a missing tool when the real message was
    right there in iconutil's stderr.

    Two details that are easy to get wrong and cost a debugging session each:

    * `iconutil` requires the staging directory to be named `*.iconset`. Any
      other name is rejected as "Invalid Iconset".
    * The staging directory lives in the system temp dir and is left there.
      The obvious `rmtree` is a recursive delete of a dozen files, and the
      name is fixed so the next build overwrites it rather than accumulating.
    """
    iconutil = iconutil_path()
    if iconutil is None:
        return IconResult(None, "iconutil not found (install Xcode command line tools)")

    iconset = Path(tempfile.gettempdir()) / ICONSET_NAME
    iconset.mkdir(parents=True, exist_ok=True)
    for size in ICONSET_SIZES:
        write_png(iconset / f"icon_{size}x{size}.png", size, size, render_icon(size))
        if size <= 512:
            double = size * 2
            write_png(
                iconset / f"icon_{size}x{size}@2x.png",
                double,
                double,
                render_icon(double),
            )

    target_dir.mkdir(parents=True, exist_ok=True)
    icns = target_dir / "AppIcon.icns"
    result = subprocess.run(
        [iconutil, "-c", "icns", str(iconset), "-o", str(icns)],
        capture_output=True,
        check=False,
    )
    if result.returncode != 0 or not icns.exists():
        detail = (result.stderr or b"").decode("utf-8", errors="replace").strip()
        return IconResult(None, f"iconutil failed: {detail[:200] or f'exit {result.returncode}'}")
    return IconResult(icns)


# ---------------------------------------------------------------------------
# bundle
# ---------------------------------------------------------------------------


@dataclass
class BundleResult:
    path: Path
    mode: str  # "launcher" | "frozen"
    python: str
    has_icon: bool
    notes: list[str]

    def summary(self) -> str:
        lines = [
            f"bundle:  {self.path}",
            f"mode:    {self.mode}",
            f"python:  {self.python}",
            f"icon:    {'yes' if self.has_icon else 'no (iconutil unavailable)'}",
        ]
        lines += [f"note:    {note}" for note in self.notes]
        return "\n".join(lines)


def build_app_bundle(
    *,
    target_dir: Path,
    version: str,
    name: str = APP_NAME,
    python: str | None = None,
    frozen: bool = False,
    console_script: str = "uaa",
) -> BundleResult:
    """Create `<name>.app` under `target_dir`."""
    if frozen:
        # Checked before the platform gate: "PyInstaller is not wired up" is
        # true on every platform, and reporting the platform first would send
        # a Linux user chasing the wrong problem.
        raise BundleError(
            "frozen bundles need PyInstaller, which is not wired up here. "
            "Install it and build with:\n"
            "  pip install pyinstaller\n"
            "  pyinstaller --windowed --name "
            f"{name} --collect-all webview "
            f"--osx-bundle-identifier {BUNDLE_ID} "
            "$(python -c 'import unified_agent,os;print(os.path.dirname("
            "unified_agent.__file__))')/desktop/__main__.py"
        )
    if sys.platform != "darwin":
        raise BundleError(
            f".app bundles are macOS-only; this is {sys.platform}. "
            "On Linux/Windows use `uaa desktop` to open the window directly."
        )

    interpreter = python or sys.executable
    final = target_dir / f"{name}.app"
    target_dir.mkdir(parents=True, exist_ok=True)

    # Build into a staging directory and swap it in with a rename. Two wins:
    # a failure halfway through never leaves a half-written app where the user
    # can double-click it, and the replacement of an existing bundle is a
    # rename rather than a recursive delete -- which some environments refuse
    # outright, and which is the kind of thing that only breaks on the second
    # build.
    staging = Path(tempfile.mkdtemp(dir=target_dir, prefix=f".{name}.building-"))
    contents = staging / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    executable = name
    launcher = macos / executable
    launcher.write_text(LAUNCHER_SCRIPT.format(python=interpreter), encoding="utf-8")
    launcher.chmod(0o755)

    (contents / "Info.plist").write_text(
        INFO_PLIST.format(
            name=name,
            display="unified-ai-agent",
            bundle_id=BUNDLE_ID,
            executable=executable,
            version=version,
            copyright=f"MIT licensed. Built by {console_script} desktop --bundle.",
        ),
        encoding="utf-8",
    )

    icon_result = build_icns(resources)

    replaced: Path | None = None
    if final.exists():
        replaced = target_dir / f".{name}.replaced-{int(time.time())}"
        os.rename(final, replaced)
    os.rename(staging, final)

    notes = [
        "launcher bundle: it runs the installed package with the interpreter "
        "above. Moving or deleting that environment breaks the app.",
        "the app writes to ~/Library/Logs/unified-ai-agent.log",
    ]
    if replaced is not None:
        try:
            shutil.rmtree(replaced)
        except (Exception, SystemExit):
            # Best-effort. A refusal here must not fail the build, but it also
            # must not be silent -- the user has a leftover directory to
            # clean up and deserves to know where it is.
            notes.append(f"could not remove the previous bundle; it is at {replaced}")
    if not icon_result:
        notes.append(f"no app icon: {icon_result.reason}")
    else:
        notes.append("icon generated procedurally (stdlib PNG + iconutil), no assets vendored")

    return BundleResult(
        path=final,
        mode="launcher",
        python=interpreter,
        has_icon=bool(icon_result),
        notes=notes,
    )


__all__ = [
    "APP_NAME",
    "BUNDLE_ID",
    "BundleError",
    "BundleResult",
    "ICONSET_NAME",
    "ICONSET_SIZES",
    "IconResult",
    "build_app_bundle",
    "build_icns",
    "iconutil_path",
    "render_icon",
    "write_png",
]
